version: '3.8'
services:
  postgres-backup:
    build: .
    image: pg-backup:latest
    environment:
      # Required
      - S3_BUCKET=my-backup-bucket
      - S3_ACCESS_KEY=your-access-key
      - S3_SECRET_KEY=your-secret-key
      - POSTGRES_CONNECTION_STRING=postgresql://user:password@host:5432/dbname
      - BACKUP_INTERVAL=0 2 * * * # Daily at 2 AM
      # Optional
      - S3_URL=https://s3.amazonaws.com
      - S3_PATH=backups
      - BACKUP_RETENTION_DAYS=30
      - LOG_LEVEL=info
    restart: unless-stopped
    # Uncomment to mount a host directory for temp files (optional)
    # volumes:
    #   - ./tmp:/tmp
